const Data = [
  {
    userId: 1,
    id: 0,
    name: "zia khan",
    desc: "Hello World this is famous",
    profession: "Developer",
  },
  {
    userId: 1,
    id: 1,
    name: "Hamza khan",
    desc: "Hello World this is famous",
    profession: "Plumber",
  },
  {
    userId: 1,
    id: 2,
    name: "Faris khan",
    desc: "Hello World this is famous",
    profession: "Painter",
  },
  {
    userId: 1,
    id: 3,
    name: "Saqib khan",
    desc: "Hello World this is famous",
    profession: "Master",
  },
  {
    userId: 1,
    id: 4,
    name: "Hamza khan",
    desc: "Hello World this is famous",
    profession: "Master",
  },
  {
    userId: 1,
    id: 5,
    name: "Irfan khan",
    desc: "Hello World this is famous",
    profession: "ABC",
  },
  {
    userId: 1,
    id: 6,
    name: "Younus khan",
    desc: "Hello World this is famous",
    profession: "Master",
  },
  {
    userId: 1,
    id: 7,
    name: "Saqib khan",
    desc: "Hello World this is famous",
    profession: "Master",
  },
  {
    userId: 1,
    id: 8,
    name: "Haffeez khan",
    desc: "Hello World this is famous",
    profession: "Master",
  },
  {
    userId: 1,
    id: 9,
    name: "Rizwan khan",
    desc: "Hello World this is famous",
    profession: "ABc",
  },
  {
    userId: 1,
    id: 10,
    name: "Saqib khan",
    desc: "Hello World this is famous",
    profession: "Master",
  },
  {
    userId: 1,
    id: 11,
    name: "Mr khan",
    desc: "Hello World this is famous",
    profession: "XYZ",
  },
  {
    userId: 1,
    id: 12,
    name: "Saqib khan",
    desc: "Hello World this is famous",
    profession: "Master",
  },
  {
    userId: 1,
    id: 13,
    name: "Sam khan",
    desc: "Hello World this is famous",
    profession: "HFg",
  },
  {
    userId: 1,
    id: 14,
    name: "Saqib khan",
    desc: "Hello World this is famous",
    profession: "Master",
  },
  {
    userId: 1,
    id: 15,
    name: "Saqib khan",
    desc: "Hello World this is famous",
    profession: "Master",
  },
];

module.exports = { Data };
